name: jesse
channels:
  - conda-forge
dependencies:
  - pip
  - numpy
  - black
  - plotly
  - nbformat
  - ipywidgets
  - fastparquet
  - optuna
  - matplotlib
  - seaborn
  - hmmlearn
  - deap
  - pip:
      - optuna-integration[lightgbm]
      - lightweight-charts
      - fasttreeshap
